#! /bin/sh

set -e

# enable ip forwarding
sysctl -w net.ipv4.ip_forward=1

##
# For volume mounts...
##
chown -R frr:frr /etc/frr || true
/usr/lib/frr/frrinit.sh start

# sleep forever
exec tail -f /dev/null
