// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: route.proto

package pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdministrativeDistance int32

const (
	AdministrativeDistance_ADConnected AdministrativeDistance = 0
	AdministrativeDistance_ADStatic    AdministrativeDistance = 1
	AdministrativeDistance_ADEBGP      AdministrativeDistance = 20
	AdministrativeDistance_ADOSPF      AdministrativeDistance = 110
	AdministrativeDistance_ADRIP       AdministrativeDistance = 120
	AdministrativeDistance_ADIBGP      AdministrativeDistance = 200
)

// Enum value maps for AdministrativeDistance.
var (
	AdministrativeDistance_name = map[int32]string{
		0:   "ADConnected",
		1:   "ADStatic",
		20:  "ADEBGP",
		110: "ADOSPF",
		120: "ADRIP",
		200: "ADIBGP",
	}
	AdministrativeDistance_value = map[string]int32{
		"ADConnected": 0,
		"ADStatic":    1,
		"ADEBGP":      20,
		"ADOSPF":      110,
		"ADRIP":       120,
		"ADIBGP":      200,
	}
)

func (x AdministrativeDistance) Enum() *AdministrativeDistance {
	p := new(AdministrativeDistance)
	*p = x
	return p
}

func (x AdministrativeDistance) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdministrativeDistance) Descriptor() protoreflect.EnumDescriptor {
	return file_route_proto_enumTypes[0].Descriptor()
}

func (AdministrativeDistance) Type() protoreflect.EnumType {
	return &file_route_proto_enumTypes[0]
}

func (x AdministrativeDistance) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdministrativeDistance.Descriptor instead.
func (AdministrativeDistance) EnumDescriptor() ([]byte, []int) {
	return file_route_proto_rawDescGZIP(), []int{0}
}

var File_route_proto protoreflect.FileDescriptor

var file_route_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67,
	0x72, 0x70, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x09, 0x67, 0x72, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x67, 0x0a, 0x16, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x76, 0x65, 0x44, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x44, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x44, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x63, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x44, 0x45, 0x42, 0x47, 0x50, 0x10, 0x14, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x44, 0x4f, 0x53, 0x50, 0x46, 0x10, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x41,
	0x44, 0x52, 0x49, 0x50, 0x10, 0x78, 0x12, 0x0b, 0x0a, 0x06, 0x41, 0x44, 0x49, 0x42, 0x47, 0x50,
	0x10, 0xc8, 0x01, 0x32, 0x40, 0x0a, 0x08, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x41, 0x70, 0x69, 0x12,
	0x34, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x2e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x72, 0x61, 0x73, 0x73, 0x79, 0x69, 0x2f, 0x67, 0x72, 0x70,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_route_proto_rawDescOnce sync.Once
	file_route_proto_rawDescData = file_route_proto_rawDesc
)

func file_route_proto_rawDescGZIP() []byte {
	file_route_proto_rawDescOnce.Do(func() {
		file_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_route_proto_rawDescData)
	})
	return file_route_proto_rawDescData
}

var file_route_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_route_proto_goTypes = []interface{}{
	(AdministrativeDistance)(0), // 0: grp.AdministrativeDistance
	(*HealthRequest)(nil),       // 1: grp.HealthRequest
	(*empty.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_route_proto_depIdxs = []int32{
	1, // 0: grp.RouteApi.Health:input_type -> grp.HealthRequest
	2, // 1: grp.RouteApi.Health:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_route_proto_init() }
func file_route_proto_init() {
	if File_route_proto != nil {
		return
	}
	file_grp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_route_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_route_proto_goTypes,
		DependencyIndexes: file_route_proto_depIdxs,
		EnumInfos:         file_route_proto_enumTypes,
	}.Build()
	File_route_proto = out.File
	file_route_proto_rawDesc = nil
	file_route_proto_goTypes = nil
	file_route_proto_depIdxs = nil
}
